### ISSUE TITLE
Elbow edges block click area for nodes in SVG

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/GPML-Repo#114]
For example, https://pathway-viewer.toolforge.org/embed/WP554

Note the big red elbow edge in the top right corner. If you draw an imaginary line from it's source to it's target, then you'll notice that you cannot click (even the mouse-over appears different) inside that triangle, but you can click the parts of the nodes outside that triangle.

This is a bug in our SVG generation. Maybe element order would fix? I really have no idea....

**Comment by larsgw** [comment]
The elbow has a higher `ZOrder` (32771) than e.g. the ACE2 node (32768) but those are not included in the SVG.

**Comment by khanspers** [comment]
This same issue is happening in [WP5094](https://github.com/wikipathways/wikipathways-help/discussions/30). Not sure it helps but here's a screenshot with all the non-clickable nodes marked with a red slash: 
<img width="1649" alt="Screen Shot 2023-04-14 at 1 25 41 PM" src="https://user-images.githubusercontent.com/1442197/232152969-4f3a2b21-43a2-419f-9251-b6a403b3b803.png">

**Comment by AlexanderPico** [comment]
I looked at the SVG for this case and can explain the non-clickable nodes. The order of objects in the SVG matters for things like clicking. In many of the cases in this pathway, the outer "group" box is listed _after_ all or most of the member nodes, so you are basically clicking the box and not the node underneath. In other cases, then elbowed path is drawn _after_ one or more nodes, thus blocking those from clicks as well.

Solution:  Update SVG generation code to draw clickable objects after other types of objects. 

Difficulty:  Hard. Hassan is planning to look at the pvjson-svg code soon. Maybe he can figure it out.

**Comment by khanspers** [comment]
Sounds like a plan. This probably affects a lot of pathways. 
In the meantime, for the ones we find, here's a quick fix that I just tried on the Orexin pathway and it works:
1. Open pathways in PV
2. Select all data nodes (Right-click, Select > Select all DataNodes)
3. Right-click on a node (with all nodes selected) and choose Order > Bring to front.

**Comment by khanspers** [comment]
Just used the same quick fix for WP554.

**Comment by AlexanderPico** [comment]
Whoa! Confirmed this fixes the SVG on the new site too. Amazing. This opens up a new solution path:  PathVisio can just automatically do this on every pathway right before "save" operations.

@khanspers Can you open this as PathVisio feature and assign Tina? I think it could fit into the next release.

**Comment by khanspers** [comment]
https://github.com/PathVisio/pathvisio/issues/192
