### ISSUE TITLE
Google CSE checks for "descriptions" in our structured data

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/GPML-Repo#116]
Google's Custom Search Engine is helping with QC! It found 9 pathways that were missing a description and notified me by email with a nice UI to fix and then trigger a validation and reindexing.

![Screen Shot 2023-02-23 at 5 39 26 PM](https://user-images.githubusercontent.com/1418193/221071011-85a3c73d-e448-4c42-a7d7-bd4f027f5480.png)

**Comment by Chris-Evelo** [comment]
I was wondering whether you know which part "structured" is used here. Is that Bioschemas?

**Comment by AlexanderPico** [comment]
Yes. It's the `schema-jsonld` that we add to the md files for search engines. It's technically just "schema.org" and not "bioschemas" as we are waiting for Google to support bioschemas.  We populate the description field directly from the GPML description.

Here's an example:
https://raw.githubusercontent.com/wikipathways/wikipathways.github.io/main/_pathways/WP14.md
(schema-jsonld content begins around halfway down)
