### ISSUE TITLE
Rotated graphical objects are rendered with incorrect placement (centerX) and sizing 

### ISSUE THREAD

**Issue by khanspers** [wikipathways/GPML-Repo#121]
Pathways with graphical objects that have been rotated from the default end up having an incorrect CenterX placement and incorrect overall size at WikiPatwhays, even though the gpml is correct. 

In the following pathway, the golgi in the middle column (bottom) has been rotated, and WP is placing it too far to the left. All 3 golgi also have a different size than in PV. See comparison between WP and what it looks like in PV below. 

In PathVisio:
<img width="1200" alt="Screen Shot 2023-03-28 at 11 03 50 AM" src="https://user-images.githubusercontent.com/1442197/228328856-a4c7641e-b004-48af-bf97-8eeeaab49ded.png">

In WikiPathways (screenshot from classic):
![Screen Shot 2023-03-28 at 11 06 37 AM](https://user-images.githubusercontent.com/1442197/228328891-4b1cb1a6-d770-4450-86f5-cf8ef126f7fc.png)

I have confirmed that PathVisio (3.3.0) is saving the gpml correctly and that the gpml at WP also has the correct coordinates. It seems to be a rendering bug.

Links here are for classic WP, but this is a problem on the new site too. Here's an example (note the golgi placement and size): [WP3676](https://www.wikipathways.org/pathways/WP3676.html)

[https://classic.wikipathways.org/index.php/Pathway:WP5350](https://classic.wikipathways.org/index.php/Pathway:WP5350)

**Comment by hasanbalci** [comment]
I experimented a bit with the viewBox property of the Golgi svg and if I change it from "0 0 100 100" to "0 0 100 150", I obtain the following result: 
This is how it looks like in PathVisio:

<img width="641" alt="pv" src="https://user-images.githubusercontent.com/22586369/235429501-fa6c5d5e-bdef-4dae-8039-8c563bbab876.png">

This is the conversion from gpml to svg with "0 0 100 150":

<img width="662" alt="convert150" src="https://user-images.githubusercontent.com/22586369/235429677-6975503e-3ca7-4895-8eb3-fe66fdc8d011.png">

This is the current conversion from gpml to svg with "0 0 100 100":

<img width="673" alt="convert100" src="https://user-images.githubusercontent.com/22586369/235429592-fd922fda-d402-46db-beac-131dd2d1450f.png">

This is not a precise solution but I think it at least generates better images.

**Comment by khanspers** [comment]
Fantastic, that's a lot better than the current behavior. So the fix would be in the svg rendering code?

**Comment by hasanbalci** [comment]
Yes, I will make the change in the svg image of Golgi.

**Comment by AlexanderPico** [comment]
@hasanbalci Close this one too?
