### ISSUE TITLE
mim-modification not correct in svg

### ISSUE THREAD

**Issue by khanspers** [wikipathways/GPML-Repo#125]
Looks like mim-modification arrow is not correct in svg. From Isabel:

"I used the mim-modification arrow to show the phosporylation in my pathway ([WP5358](https://classic.wikipathways.org/index.php/Pathway:WP5358)), but there seems to be an error somewhere. In PathVisio, the arrow looks correct and I have checked to make sure it is the modification arrow: 
![Schermafbeelding 2023-04-25 om 13 15 14](https://user-images.githubusercontent.com/123644649/234260309-bd08aa7b-00b7-4bee-8c68-ae2f64521442.png)

However, on WikiPathways (I checked both the classic and new website), the arrow looks like this, even after trying again in PathVisio:
![Schermafbeelding 2023-04-25 om 13 17 28](https://user-images.githubusercontent.com/123644649/234260730-b13e9994-774e-488a-89d3-16a686c4a838.png)
Is there a way I can resolve this issue?"

_Originally posted by @IsabelWassink in https://github.com/wikipathways/wikipathways-help/discussions/32#discussioncomment-5718651_

**Comment by AlexanderPico** [comment]
The fix would be somewhere in the pvjson code that runs in the json-svg job in the on_gpml_change.yml workflow.  That code translates Java graphical objects (like arrowheads) into SVG graphical objects.  I think @hasanbalci is looking into this code base, so assigning him for now.

**Comment by hasanbalci** [comment]
Is there a difference between the arrow heads of mim-modification and mim-binding? They look the same in PathVisio and if they really are, I can change its svg to make it the same as mim-binding.

**Comment by khanspers** [comment]
Yes, mim-modification and mim-binding use the same arrow head.

**Comment by AlexanderPico** [comment]
@hasanbalci Go ahead and close this ticket if done.
