### ISSUE TITLE
How to support permalinks and publishing

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/GPML-Repo#18]
While we don't necessarily have to support the viewing of _every_ revision of every pathway, we do need to support these cases:
 * legacy permalinks pointing to specific revisions 
 * intentions to generate and publish new permalinks

Do these pathway page views require an interactive pathway widget (i.e., the availability of PVJSON-based SVGs on toolforge) or are static images sufficient?

**Comment by AlexanderPico** [comment]
We are swapping our MySQL database and Mediawiki platform for Git and Jekyll. While Git can obviously handle the full revision history of each pathway, the Jekyll system can not maintain a processed MD file for _every_ revision of every pathway. It just can't scale to that degreee. 

I would argue that we don't really need that, however.  Old revisions could be handled in a number of alternative ways. Here are a few to start the brainstorm:

1. We could store static HTML versions of every page that are viewed separately from the main site. These pages should have links to the live site. They would include embedded PNGs instead of interactive pathway viewers.
2. We could only store a subset of revisions, i.e., those that have been requested in the past (scraped from our logs) and those that are requested in the future. These could be veiwed as static pages on a separate site with embedded PNGs. 
3. Going forward, when someone wants to publish a permalink, we could generate the static site and then guide them to publish it via FigShare or something similar so that we aren't responsible for hosting the permalink at all! This would result in a DOI and other good things we'd want for this use case anyways.

Other ideas?

**Comment by AlexanderPico** [comment]
Related to idea 3, @egonw shared this post about registering blog posts for DOIs using GitHub Actions: https://blog.front-matter.io/posts/registering-content-with-crossref-or-datacite. This could work for us too, right? 

- User clicks on "Get publishable link" on a given pathway page
- This triggers a GitHub Action to register the page
- The user gets a DOI

**Comment by khanspers** [comment]
For new permalinks, the GitHub actions approach seems the easiest from the user's perspective. 

For legacy permalinks, the separate site with a smaller set of static htmls seems best, assuming our logs are reliable in terms of capturing all previously requested revisions.

This brings up another question about general viewing of previous revisions on the new site:
Since there won't be an md file for each of these, what happens when a user tried to view a revision? Is a static HTML with embedded png generated on the fly? I think that's what you mean in point 1 in the previous comment.

**Comment by AlexanderPico** [comment]
<img width="592" alt="Screenshot 2023-05-12 at 12 34 10 PM" src="https://github.com/wikipathways/wikipathways-development/assets/1418193/c91e7baa-4502-4170-98e1-ce748bc251a3">
