### ISSUE TITLE
Help/Documentation

### ISSUE THREAD

**Issue by khanspers** [wikipathways/GPML-Repo#19]
We should identify which part of the [current content ](https://www.wikipathways.org/index.php/Help:Contents) are useful and should be either 1) transferred to github site in some form 2) converted to reveal tutorials to be linked to from github site 3) already covered by other content (i.e. PathVisio etc).

The overall idea is to simplify and streamline the content, and to NOT create too many pages at the github site.

**Comment by khanspers** [comment]
Planning doc: https://docs.google.com/spreadsheets/d/1Ko9eLliQ5wbokioJyXTVfC9VtnPmoBYtyF38sX9ThDg/edit#gid=1551451845

**Comment by khanspers** [comment]
Update: We will skip reveal and instead use Google Slides. 
One idea is to create a Google Slides deck for each of the three main topics in the  [current content](https://www.wikipathways.org/index.php/Help:Contents) (roughly): Biologists and Chemists, Pathway Authors, Developers.

**Comment by khanspers** [comment]
Proposed plan:
The front page Learn section has 4 links with topics that can each lead to dedicated content: 

How to Contribute: Either a dedicated page OR linkout to Google slide deck
How to Curate: link to Academy (done)
How to Use: linkout to Google slide deck
How to Develop: linkout to Google slide deck

I will start drafts of these and will add links here as they become available. Open to any feedback on the overall plan or details.

**Comment by khanspers** [comment]
Front page has been updated:
- Added two buttons to Download: Download gene sets and Download images
- Added How to Analyze button under Analyze, linked to new page: https://new.wikipathways.org/analyze.html
- Added How to Publish button under Publish (no link yet)
- Changed Learn to Contribute
- Linked How to Contribute to new page: https://new.wikipathways.org/contribute.html

To-Do:
Update the list on Analyze page to include some sort of bullet

**Comment by khanspers** [comment]
FAQ has been added here: https://github.com/wikipathways/wikipathways-help/discussions

**Comment by khanspers** [comment]
What we have so far:
How to contribute: https://new.wikipathways.org/contribute.html (linked to from Create on front page)
Analyze: https://new.wikipathways.org/analyze.html (linked to from Analyze on front page)
FAQ: https://github.com/wikipathways/wikipathways-help/discussions (not linked to right now)

What we still need:
How to Publish
Intro tutorial

Unclear:
Do we still need this page: https://new.wikipathways.org/help.html
If yes, then it should be redesigned with the same terminology as elsewhere (Create, Curate, Analyze etc). 
If no, then update links to Help to something else.

**Comment by Chris-Evelo** [comment]
I would think: "yes we need that". While it is good to link to a more specific help page for every activity. People might still want o study the whole thing starting with "help". For that same reason, it is also to link to a page describing tutorials from that help page.

**Comment by khanspers** [comment]
I updated the [Help page](https://new.wikipathways.org/help.html). If there are specific things that should be covered on this page, please list them in this issue. Keep in mind that we are trying to link out to existing content or other pages as mush as possible, to keep the main Help page short and concise.

**Comment by AlexanderPico** [comment]
Agreed. How about these sections (each can be brief outlines, like the current ones, and link out for details): 
* Navigate - how to use the web site (e.g., what you can search for, different ways to browse, url patterns, etc)
* Create - _already started_
* Curate - the types of things we check as curators; contact info to join curation roster
* Code - we should have a Contribute.md on wp-dev repo
* Analyze - _already started_
* Publish - url patterns, copy link to cliipboard icon, citations, NDEx-minted DOIs for specific versions and data vis
* FAQ - _already started_

**Comment by AlexanderPico** [comment]
_Pro-tip_. If you wrap each section in a `<div id="analyze">...</div>` then we can link with anchors like https://new.wikipathways.org/help.html#analyze

**Comment by khanspers** [comment]
The FAQ is done for now: https://github.com/wikipathways/wikipathways-help/discussions
To-Do for the remaining [items](https://docs.google.com/spreadsheets/d/1Ko9eLliQ5wbokioJyXTVfC9VtnPmoBYtyF38sX9ThDg/edit?usp=sharing):
- Option 1: Add remaining FAQ topics now, with the answers for how it currently works on the wiki
- Option 2: Add remaining items later, when we know how it will work on the new site.

- Additionally, content is being added to the Academy. Some of these can later be added to FAQ with links to the Academy.

**Comment by khanspers** [comment]
Here's the current status and timeline. Also, it would be great to have others review these pages for content, clarity etc.

1. Help page (https://new.wikipathways.org/help.html)

- **Navigate - To-Do: Add content for searching (e.g., what you can search for, different ways to browse, url patterns, etc). Timeline: Draft by June 10**.
- Create - Done. New link added to PathVisio YouTube channel and added a direct link to Contribute page. 
- Curate - Done
- **Code - To-Do: we should have a Contribute.md on wp-dev repo**
- Analyze - Done
- **Publish - To-Do: Add url patterns, copy link to clipboard icon, citations, NDEx-minted DOIs for specific versions and data vis. Timeline: Draft by June 10**.
- FAQ - Done, all relevant content transferred to https://github.com/wikipathways/wikipathways-help/discussions

2. Contribute page https://new.wikipathways.org/contribute.html: Done.

4. Other static pages related to Help:

- Cite - https://new.wikipathways.org/cite.html. **Could benefit from review**.
- Terms of Use - https://new.wikipathways.org/terms.html. **Could benefit from review**.

**Comment by khanspers** [comment]
Update: Navigate and Publish have been updated. The only thing missing from the original list is **NDEx-minted DOIs for specific versions** which I don't know how to do.

**Comment by AlexanderPico** [comment]
> Update: Navigate and Publish have been updated. The only thing missing from the original list is **NDEx-minted DOIs for specific versions** which I don't know how to do.

Currently, the only way is to email Dexter. But they are planning to add a button at some point.

**Comment by khanspers** [comment]
Should I add a sentence or two describing it, with Dexter’s contact?

Kristina

**Comment by AlexanderPico** [comment]
Nope. Just ignore for now.
