### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/GPML-Repo#20]
Here are a few ways we can do badges on our new site. [Shields.io](https://shields.io/) supports the following cases where the content is sourced from:

- GitHub | Jenkins | CircleCI | Uptime | etc, e.g., build status, contributors, commits, etc 
- Front Matter variables, e.g., last-edited timestamp that we write at the time of PR approval
- JSON, e.g., custom content that is updated asynchronously with Jekyll

This example page includes a few examples of these:  https://wikipathways.github.io/pathways/WP554.html
 - (pathway) last edited from from a [Front Matter variable](https://raw.githubusercontent.com/wikipathways/wikipathways.github.io/main/_pathways/WP554.md). **_Note: useful for stuff we get from GPML and from PR process, i.e., when the .md file is being written._**
 - (pathway) status comes from a [JSON file](https://github.com/wikipathways/repository/blob/main/WP554/status.json). **_Note: we can use this to note when a PR is under review or if we want to display a lock for editors, and other stuff that doesn't other require a Jekyll recompile_**
 - (footer) GitHub examples.  **_Note: the "check" badge is handy as it displays as "pending" while Jekyll is in the process of rebuilding._**

Other ideas?

**Comment by egonw** [comment]
* curation status
* number of citations to this pathway
