### ISSUE TITLE
GH Action to update plain text file with all WP identifiers

### ISSUE THREAD

**Issue by egonw** [wikipathways/GPML-Repo#21]
one of each line, for all pathways in the repo. Autogenerated each time the Markdown is created.

Use: downstream tools to provide information about the pathways, like the pathway curations tools.

**Comment by AlexanderPico** [comment]
Here's the current version:
https://github.com/wikipathways/wikipathways-database/blob/main/wpid_keep_list.txt

It is generated by looking up the "Analysis" tag currently (see [script](https://github.com/wikipathways/wikipathways-database/blob/main/scripts/wpid_keep_list.R)), but should be generated by GitHub Action when pathways are added or removed.

Leave this ticket open until that autogeneration is complete.

**Comment by AlexanderPico** [comment]
added to on_gpml_change:yml
https://github.com/wikipathways/wikipathways-database/blob/main/.github/workflows/on_gpml_change.yml#L62

**Comment by AlexanderPico** [comment]
The updated list is accessible via this link:
https://raw.githubusercontent.com/wikipathways/wikipathways-database/main/wpid_list.txt
