### ISSUE TITLE
What to do with homology converted content

### ISSUE THREAD

**Issue by khanspers** [wikipathways/GPML-Repo#36]
We have decided to NOT include homology converted content to start off. 

Current ideas on how to deal with homology converted content (from meeting notes):
- Current content: Separate edited content from purely converted. Edited should “stay” in main branch; converted should be in a separate repo.
- On-demand tool idea:  Start species 	|  version | Target Species | format
- Have a repo of homology converted content for folks to browse 
- Export “extended” sets of pathways in GPML and GMT formats in monthly release

Spreadsheet with revision info on all Homology tagged content. Note that this doesn't include pathways that are homology converted but missing the tag (need to add this):
https://docs.google.com/spreadsheets/d/1DHX_FbSwmeTxOXp8ar5BmGKQtOSYriUTtzYajjAlg8c/edit#gid=632216275
- This is based on the "getEveryCurationTag" method, so it includes all pathways tagged as Homology.
- The last two columns show the revision number for the tagged revision and the latest, to deduce which pathways have been updated since it was last tagged (19 of 152)

**Comment by AlexanderPico** [comment]
Excellent! I added a column to track decisions to "keep" using the Approved tag (like we did with the other sheet). I am making the tag changes to the pathways as I go.  

Others can feel free to review and reverse these decisions, but at least it gets us to a place where we can start using the Approved tag to define the set we're maintaining in the new site.

**Comment by Chris-Evelo** [comment]
What is the consequence of this for collaborators like Zahra, who works with homology converted content (cow) almost exclusively?

**Comment by AlexanderPico** [comment]
They will have a regularly updated repo of homology converted content rather than stale, confused content mixed in with manually curated stuff.  If they have manually curated any cow pathways, then those should be kept in the curated repo.

@Chris-Evelo it's great that you know the folks using these. Do you know if they use the GMT or the website or webservices or ... ?  We can make sure to prioritize those first for the homology use case.

**Comment by AlexanderPico** [comment]
Here's the new homology repo with all the current content that is *only* homology mapped and not customized by curation:  https://github.com/wikipathways/wikipathways-homology

We should build upstream and downstream tools off of this database repo, just like we are doing for the main `wikipathways-database` repo. For example, future runs of the homology converter can dump GPML here. We can generate  .gmt files of homology content and distribute them at data.wikipathways.org. Etc...

**Comment by Chris-Evelo** [comment]
Sounds good. I was afraid they would not be available at all. 

Zahra visited us a while ago and she wrote this paper: https://doi.org/10.3389/fgene.2019.01370 

She used the homology converted pathways and created a few new ones specifically related to the marbling process (which relates to fat present in muscles and affects meat quality). She was trained by and worked with Susan. She can use the edit and analysis functions of PathVisio but I do not think much beyond that.
