### ISSUE TITLE
Define strategy for bulk changes to many GPML files programmatically and how actions should deal with that

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/GPML-Repo#40]
There is a max of actions that can run at the same time so we should consider what to do in those situations

**Comment by ariutta** [comment]
TODO: what happens with the concurrency here?
https://github.com/wikipathways/wikipathways-database/blob/8918bc73d79c766d115b95491b44294bf9ef06db/.github/workflows/on_communities_change.yml#L11-L13

**Comment by AlexanderPico** [comment]
Indeed, we cannot trigger a GH Action for every GPML edit pushed by PV4 as a Pull Request. That certainly overload our Actions quota. However, this strategy should resolve it:

1. PV4 will use API to create and update PRs to wp-db repo
2. The repo can control GH Action frequency (e.g., by triggering hourly) to check for new PRs with GPML files
3. The Action will perform QC checks and generate associated files (including SVG, PNG, JSON and TSVs).
4. PRs will either be automatically merged (all checks pass; trusted author), or assigned to a Curator of the Week for review.
