### ISSUE TITLE
front page design

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/GPML-Repo#48]
brainstorm on modern landing pages:
 - https://discord.com/nitro
 - https://trello.com/
 - https://eonreality.com/
 - https://happyegg.com/
 - https://www.krissrealestate.com/
 - https://www.zume.com/
 - https://www.mailpoet.com/
 - https://emol.work/
   - full page header
   - text and buttons left; image right
   - scroll for cards or full width sections
 - general UI/UX design trends
    - fast page load
    - little clutter (use white space)
    - mobile responsiveness
    - good use of SEO
    - multimedia
    - easy-to-read content; easy-to-use interfaces
    - image captions (functional/educational/purposeful interactivity)
    - muted color and gradient backgrounds; vibrant color actions

**Comment by AlexanderPico** [comment]
![wp landing v3](https://user-images.githubusercontent.com/1418193/156940886-91037094-89e7-45f9-b882-125027b16d69.png)

**Comment by AlexanderPico** [comment]
https://new.wikipathways.org/home2

**Comment by AlexanderPico** [comment]
@khanspers Could you help me collect screenshots for the slideshows in the mockup? They should represent the main options or results of each section. They should all be 450x450px (or otherwise square at higher px count, e.g,. 934x934).

Let's add them to wikipathways.github.io/assets/img/slideshow with names like `browse-1.png`, `download-1.png` and `analyze-1.png`. Let's target between 3 and 6 per section.

**Comment by AlexanderPico** [comment]
Completed slideshows and initial draft of new home. Find old home at https://new.wikipathways.org/alt_home.html

**Comment by AlexanderPico** [comment]
Notes from Graphics Dept...
![newwikipathwaysorg](https://user-images.githubusercontent.com/1418193/158708421-ef8274c2-ff72-4ac9-8abd-0f1a8fc0f488.jpg)

**Comment by khanspers** [comment]
> @khanspers Could you help me collect screenshots for the slideshows in the mockup? They should represent the main options or results of each section. They should all be 450x450px (or otherwise square at higher px count, e.g,. 934x934).
> 
> Let's add them to wikipathways.github.io/assets/img/slideshow with names like `browse-1.png`, `download-1.png` and `analyze-1.png`. Let's target between 3 and 6 per section.

@AlexanderPico : Looks like you did this already, sorry. It fell off my radar. Is there anything else needed right now for this?

**Comment by AlexanderPico** [comment]
No worries, @khanspers, you have your hands full with help and other doc pages!  The new front page is done, as far as I can tell. If you have any feedback for improvements, please let me know.
