### ISSUE TITLE
Search appears to be broken

### ISSUE THREAD

**Issue by khanspers** [wikipathways/GPML-Repo#54]
Search terms that worked previously, like WP554 and ACE, don't produce any results. The popup simply says "No results".

**Comment by AlexanderPico** [comment]
Yep. Google isn't indexing anything from the new site at this time. Something got messed up... I think I have to register a new domain in the dashboard or something.

It's on my to-do list.

**Comment by AlexanderPico** [comment]
Ok. I think it's setup properly again. Google CSE is showing 1.2k valid indexed pages. The search isn't working yet, but I think it's just a matter of waiting a day or two...

**Comment by AlexanderPico** [comment]
Found typo deep in config for CSE. Fixed!
