### ISSUE TITLE
Add remaining community pages

### ISSUE THREAD

**Issue by khanspers** [wikipathways/GPML-Repo#74]
Some portals are still missing and need to be added.

- Disease: 80 pathways, overlaps with Rare Disease and COVID-19. Do we really need this?
- exRNA: 75 pathways
- Micronutrients: 9 pathways
- Nanomaterials: 6 pathways
- Plant: 148 pathways. 
- Renal Genomics: 27 pathways, some in multiple species.
- Reactome

**Comment by khanspers** [comment]
Micronutrients done: https://new.wikipathways.org/communities/micronutrients.html

**Comment by khanspers** [comment]
All portal pages that were listed in meeting notes have now been moved over. Tagging responsible admins here.

Daphnia: https://new.wikipathways.org/communities/daphnia.html (no pathways yet because its human only -> remove?) @marvinm2 

Diseases: https://new.wikipathways.org/communities/diseases.html @DeniseSl22 

Nanomaterials: https://new.wikipathways.org/communities/nanomaterials.html @egonw 

Reactome: https://new.wikipathways.org/communities/reactome.html (no pathways yet because wikipathways-database doesn't contain Reactome pathways) @DeniseSl22 

Renal Genomics: https://new.wikipathways.org/communities/renal_genomics.html

**Comment by egonw** [comment]
> Daphnia: https://new.wikipathways.org/communities/daphnia.html (no pathways yet because its human only -> remove?) @marvinm2

https://www.wikipathways.org/index.php/Pathway:WP5077 and https://www.wikipathways.org/index.php/Pathway:WP5237 are Daphnia pathways.

I see these two are added, but the point is that since we only have Human pathways right now, only Human Communities make sense right now?

**Comment by khanspers** [comment]
Actually, all approved pathways are on the new site, but the two Daphnia pathways are still under construction. If you can complete them, I can add them to the wikipathways-database repo. @egonw

**Comment by AlexanderPico** [comment]
Yes, all species are in the new site, but only approved pathways as of ~Feb 22 (when I last manually sync'd). We are indeed missing  pathways newly approved since Feb.

**Comment by egonw** [comment]
> Actually, all approved pathways are on the new site, but the two Daphnia pathways are still under construction. If you can complete them, I can add them to the wikipathways-database repo. @egonw

Ah, right. I'll fix them up asap.

**Comment by egonw** [comment]
@khanspers, I discussed the (Rara) Disease portal situation with Freddie and Denise. Conclusion was that we like to keep both. Freddie will take care of the content; I'll help here with technical aspects, if needed.
