### ISSUE TITLE
metadata task is broken

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/GPML-Repo#78]
[echoed from Slack]
The metadata task in our GitHub Actions is broken. The last time it ran successfully was [9 June ](https://github.com/wikipathways/wikipathways-database/runs/6808243188?check_suite_focus=true)and it hasn’t been attempted again (with an actual GPML change) until today. The step that is failing is git pull [here](https://github.com/wikipathways/wikipathways-database/blob/main/.github/workflows/on_gpml_change.yml#L141) and an example error is [here](https://github.com/wikipathways/wikipathways-database/runs/7366469062?check_suite_focus=true#step:7:50).

I’ve tried alternative ways to set the git user.name and user.email, and alt ssh-agent action, and the v3 of actions/checkout. I’ve tried minor edits to 3 different pathways. None of these have worked.

**Comment by larsgw** [comment]
I seem to recall GitHub deprecating some form of non-SSH authentication but I can't find the source anymore. The metadata job does not have an ssh-agent at all at the moment, so that might be the problem.

**Comment by egonw** [comment]
The problem seems to be that the the `cache` step was removing the git metadata, making the pull/push not see any git info and therefore fail to push. Reordering the caching and the checking out of git seems to solve it. See Slack for more detail and my patches from last night.
