### ISSUE TITLE
Weekly updating display of "Community Editor" 

### ISSUE THREAD

**Issue by khanspers** [wikipathways/GPML-Repo#84]
Assuming we want to have some version of the "Curator of the Week" display on the new site, here are some ideas:

1. In the Curate section of Help, add a right-aligned "Community Editor of the Week" div with photo and name/affiliation. This would require weekly manual updates of the page.
2. Link to the weekly [curation reports](https://github.com/wikipathways/wikipathways-development/discussions/categories/curation-reports). The weekly discussion entries show the author/editor, although not with a large photo and affiliation. Maybe we can add a pinned discussion that gets updated each week with name and affiliation? 

Please add other ideas here.

**Comment by AlexanderPico** [comment]
My initial reaction was that this rotation needs to be automated, maybe using a gallery widget. But, maybe the manual aspect is a plus here. It would essentially be like having the Community Editor of the Week **_sign in_** at the beginning of their week. With our PR approach to curation, we will need to break our habit of saving all the work until Friday (or Saturday) and instead try to keep up with PRs as they come in during the week.

So, the sign-in procedure could be editing a single document, which then triggers these other actions automatically:
 * GitHub Action to notify a particular person with each PR
 * Updated the Curate section of Help (1. from above)
 * Update or make a new post to the Discussions where curation reports go (2. from above)

**Comment by AlexanderPico** [comment]
Let's start by making a "community_editors" folder in the github.io repo and adding a few photos and an `active.md` file that contains the name of an editor and photo filename.  Then we can modify the Help page to pull from there and other tasks can potentially pull from there as well.

**Comment by khanspers** [comment]
Good plan. I've added the folder, photos and md file.

**Comment by khanspers** [comment]
This is done.
